name: Create draft release with compiled files

on:
  workflow_dispatch:

jobs:
  compile_dll:
    runs-on: windows-latest
    env:
      GITHUB_USERNAME: ${{ secrets.USERNAME }}
      GITHUB_TOKEN: ${{ secrets.TOKEN }}
    
    steps:
      - name: Check out project
        uses: actions/checkout@v4

      - name: Set up GraalVM CE 23
        uses: graalvm/setup-graalvm@v1
        with:
          distribution: 'graalvm'
          edition: 'ce'       # Community Edition
          java-version: '23.0.2'
          components: 'native-image'  # Installerer Native Image
          cache: 'maven'

      - name: Build with Maven (native)
        shell: cmd
        run: |
          set PATH=%JAVA_HOME%\bin;%PATH%
          cd java_graal
          ./mvnw -B package -Pnative --file pom.xml -ntp

      - name: create staging and copy
        shell: cmd
        run: |
          cd java_graal
          mkdir staging
          copy target\*.dll staging\
          copy target\*.h   staging\
          copy target\*.lib staging\

      - name: Create draft release
        uses: ncipollo/release-action@v1.11.2
        with:
          token: ${{ env.GITHUB_TOKEN }}
          name: NeqSim
          tag: 23
          draft: true
          generateReleaseNotes: true
          skipIfReleaseExists: false
          artifacts: "java_graal/staging/*.*"
