name: Run Integration Tests

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  integration_tests:
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    permissions:
      contents: read
      packages: read

    env:
      # Used by java_graal/settings.xml to access GitHub Packages, if needed
      GITHUB_USERNAME: ${{ github.actor }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Check out project
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Java 21
        uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9 # v4.8.0
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Run integration-tagged tests
        working-directory: java_graal
        run: ./mvnw -B test --file pom.xml -ntp -Dsurefire.excludedGroups=
