name: Create Linux Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
        default: '1.0.0'

jobs:
  compile_and_release_linux:
    runs-on: ubuntu-latest
    env:
      GITHUB_USERNAME: ${{ secrets.USERNAME }}
      GITHUB_TOKEN: ${{ secrets.TOKEN }}

    steps:
      - name: Check out project
        uses: actions/checkout@v4

      - name: Set up GraalVM CE
        uses: graalvm/setup-graalvm@v1
        with:
          distribution: 'graalvm'
          edition: 'ce'
          java-version: '24.0.0'
          components: 'native-image'
          cache: 'maven'

      - name: Print native-image version
        run: |
          native-image --version

      - name: Install local neqsim JAR
        run: |
          cd java_graal
          for f in neqsim-*.jar; do
            echo "Installing $f"
            version=$(echo $f | cut -d '-' -f2 | cut -d '.' -f1-3)
            mvn org.apache.maven.plugins:maven-install-plugin:3.1.1:install-file \
              -Dfile="$f" \
              -DgroupId=com.equinor.neqsim \
              -DartifactId=neqsim \
              -Dversion="$version" \
              -Dpackaging=jar
          done

      - name: Build native shared library
        run: |
          cd java_graal
          ./mvnw -B package -Pnative --file pom.xml -ntp

      - name: Prepare release files
        run: |
          cd java_graal
          mkdir -p release-assets
          cp target/neqsim.so release-assets/
          cp target/neqsim.h release-assets/
          cp target/graal_isolate.h release-assets/

      - name: Upload release files
        uses: actions/upload-artifact@v4
        with:
          name: linux-release
          path: java_graal/release-assets/*.*

  release:
    runs-on: ubuntu-latest
    needs: compile_and_release_linux
    steps:
      - name: Check out project
        uses: actions/checkout@v4

      - name: Download compiled artifacts
        uses: actions/download-artifact@v4
        with:
          name: linux-release
          path: release-assets

      - name: Create Linux draft release
        uses: ncipollo/release-action@v1.13.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: NeqSim Linux v${{ github.event.inputs.version }}
          tag: v${{ github.event.inputs.version }}-linux
          draft: true
          generateReleaseNotes: true
          replacesArtifacts: true
          artifacts: release-assets/*
